CSTplatform/urls.py
# -*- coding:utf-8 -*-
"""CSTplatform URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.views.static import serve
from CSTplatform.settings import MEDIA_ROOT
from django.views.generic import TemplateView
# from django.contrib import admin

import xadmin

from users.views import LoginView, RegisterView, ActiveUserView, LogoutView
from goods.views import IndexView


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),

    # 用户相关url的配置
    url(r'^users/', include('users.urls', namespace="users")),

    # 商品相关url配置
    url(r'^goods/', include('goods.urls', namespace="goods")),

    # 用户操作相关url配置
    url(r'^operation/', include('operation.urls', namespace="operation")),

    # 上传文件的访问处理配置
    url('^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # 验证码
    url(r'^captcha/', include('captcha.urls')),
]

# 全局404, 500页面配置
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/goods/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url

from .views import BooksListView, ToolsListView, EleProductsListView, OthersListView
from .views import BookDetailView, ToolDetailView, EleProductDetailView, OtherDetailView


urlpatterns = [
    # 列表页
    url(r'^books/list/$', BooksListView.as_view(), name="book_list"),
    url(r'^tools/list/$', ToolsListView.as_view(), name="tool_list"),
    url(r'^eleproducts/list/$', EleProductsListView.as_view(), name="eleproduct_list"),
    url(r'^others/list/$', OthersListView.as_view(), name="other_list"),

    # 商品详细页
    url(r'^books/detail/(?P<id>\d+)/$', BookDetailView.as_view(), name="book_detail"),
    url(r'^tools/detail/(?P<id>\d+)/$', ToolDetailView.as_view(), name="tool_detail"),
    url(r'^eleproducts/detail/(?P<id>\d+)/$', EleProductDetailView.as_view(), name="eleproduct_detail"),
    url(r'^others/detail/(?P<id>\d+)/$', OtherDetailView.as_view(), name="other_detail"),
]

apps/operation/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url

from .views import UserFavoriteView, PubInfoView, SearchView
from .views import GoodsDelView, GoodsFavDelView, UserFavDelView


urlpatterns = [
    url(r'^userfav/$', UserFavoriteView.as_view(), name="user_fav"),
    url(r'^pubinfo/$', PubInfoView.as_view(), name="pubinfo"),
    url(r'^search/(?P<name>.*)$', SearchView.as_view(), name="search"),
    url(r'^goods/del/(?P<id>\d+)$', GoodsDelView.as_view(), name="goods_del"),
    url(r'^fav/del/(?P<fav_id>\d+)$', GoodsFavDelView.as_view(), name="fav_del"),
    url(r'^userfav/del/(?P<fav_id>\d+)$', UserFavDelView.as_view(), name="userfav_del"),
]

apps/users/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url

from .views import SendEmailView, ForgetpwdView, ResetView
from .views import PersonalView, UserFavView, GoodsFavView
from .views import UserInfoAlterView, UserInfoSaveView, AlterPasswordView


urlpatterns = [
    url(r'^sendemail/$', SendEmailView.as_view(), name="sendemail"),
    url(r'^resetpwd/(?P<active_code>.*)', ResetView.as_view(), name="resetpwd"),
    url(r'^forgetpwd/$', ForgetpwdView.as_view(), name="forgetpwd"),
    url(r'^personal/$', PersonalView.as_view(), name="personal"),
    url(r'^userfav/$', UserFavView.as_view(), name="userfav"),
    url(r'^goodsfav/$', GoodsFavView.as_view(), name="goodsfav"),
    url(r'^userinfoalter/(?P<id>\d+)$', UserInfoAlterView.as_view(), name="userinfoalter"),
    url(r'^userinfosave/$', UserInfoSaveView.as_view(), name="userinfosave"),
    url('^alterpassword/$', AlterPasswordView.as_view(), name="alterpassword"),
]

apps/goods/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from users.models import UserProfile
# Create your models here.


class Goods(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u"发布者学号", default=u"")
    goods_title = models.CharField(max_length=50, verbose_name=u"标题")
    price = models.CharField(max_length=20, verbose_name=u"价格")
    oprice = models.CharField(max_length=20, verbose_name=u"原价")
    address = models.CharField(max_length=50, verbose_name=u"地址")
    phone = models.CharField(max_length=11, verbose_name=u"手机号")
    description = models.CharField(max_length=500, verbose_name=u"商品描述")
    category = models.IntegerField(verbose_name=u"商品分类", choices=((1, u"书籍类"), (2, u"机动类"), (3, u"电子产品"), (4, u"其他")), default=1)
    is_delete = models.BooleanField(default=False, verbose_name=u"逻辑删除")
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u"商品信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.goods_title


class GoodsImage(models.Model):
    goods = models.ForeignKey(Goods, verbose_name=u"商品", null=True, blank=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to="images/%Y_%m", default="img/default_middile_2.png", verbose_name=u"商品实体图片", max_length=100)
    is_delete = models.BooleanField(default=False, verbose_name=u"逻辑删除")
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u"商品实体图"
        verbose_name_plural = verbose_name

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活失败</title>
</head>
<body>
激活链接失效，请联系管理员解决
</body>
</html>

templates/book_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    书籍类列表
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block bread %}
<section class="bread">
    <div class="row">
        <div class="col-lg-offset-1 col-lg-10">
            <div class="breadDiv">
                <span><a href="{% url 'index' %}">首页</a></span><span>&nbsp;>&nbsp;</span><span>二手书籍</span>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="content">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <ul class="contentul">
            {% for book in goods_books %}
            <li class="contentli">
                <div class="col-lg-12 {% if forloop.first %} contentDiv1 {% else %} contentDiv2 {% endif %}">
                    <div>
                        <div class="contentleft">
                            <a href="{% url 'goods:book_detail' book.id %}"><img src="{{ MEDIA_URL }}{{ book.goodsimage_set.all.first.image }}"/></a>
                        </div>
                        <div class="contentright">
                            <p><a href="{% url 'goods:book_detail' book.id %}">{{ book.goods_title }}</a><span>{{ book.price }}</span></p>
                            <p>{{ book.description | slice:":30" }}.......</p>
                            <br>
                            <p>发布时间：{{ book.add_time|date:"Y-m-d" }}</p>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}

        </ul>
    </div>
</div>
</section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load poll_extras %}
{% block content %}
<!--赞助商广告-->
<section class="advertising">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
    <div class="imageSlider">
        <div class="imageBox">
            {% for banner in all_banners %}
            <a href="{{ banner.url }}" target="_blank"><img src="{{ MEDIA_URL }}{{ banner.image }}" /></a>
            {% endfor %}
        </div>

        <div class="titleBox">
            {% for banner in all_banners %}
                {% if forloop.first %}
                    <p class="active"><span>{{ banner.title }}</span></p>
                {% else %}
                    <p>{{ banner.title }}</p>
                {% endif %}
            {% endfor %}
        </div>

        <div class="icoBox">
            {%  for i in all_banners.count|list %}
                {% if forloop.first %}
                    <span class="active" rel="{{ i }}">{{ i }}</span>
                {% else %}
                    <span rel="{{ i }}">{{ i }}</span>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    </div>
</div>
</section>

<!--书籍类最新发布-->
<section class="books">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 HeaderHeight">
        <div class="col-lg-2">
            <p><strong>二手书籍</strong></p>
        </div>
        <div class="col-lg-2 col-lg-offset-7">
            <p><a href="{% url 'goods:book_list' %}"><strong>更多二手书籍</strong></a></p>
        </div>
    </div>
    <div class="col-lg-10 col-lg-offset-1 BodyHeight">
        <div class="Info">
            {% for book in goods_books %}
                <div class="goods {% if forloop.counter == 1 or forloop.counter == 6 %} six {% endif %}">
                    <a href="{% url 'goods:book_detail' book.id %}"><img src="{{ MEDIA_URL }}{{ book.goodsimage_set.all.first.image }}"/></a><p>{{ book.goods_title }}</p>
                    <span class="price">{{ book.price }}</span><span>{{ book.add_time|date:"Y-m-d" }}</span>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
</section>

<!--工具类最新发布-->
<section class="tools">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 HeaderHeight">
            <div class="col-lg-2">
                <p><strong>二手机动</strong></p>
            </div>
            <div class="col-lg-2 col-lg-offset-7">
                <p><a href="{% url 'goods:tool_list' %}"><strong>更多二手机动</strong></a></p>
            </div>
        </div>
        <div class="col-lg-10 col-lg-offset-1 BodyHeight">
            <div class="Info">
                {% for tool in goods_tools %}
                    <div class="goods {% if forloop.counter == 1 or forloop.counter == 6 %} six {% endif %}">
                        <a href="{% url 'goods:tool_detail' tool.id %}"><img src="{{ MEDIA_URL }}{{ tool.goodsimage_set.all.first.image }}"/></a><p>{{ tool.goods_title }}</p>
                        <span class="price">{{ tool.price }}</span><span>{{ tool.add_time|date:"Y-m-d" }}</span>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<!--电子产品-->
<section class="eleProduct">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 HeaderHeight">
            <div class="col-lg-2">
                <p><strong>电子产品</strong></p>
            </div>
            <div class="col-lg-2 col-lg-offset-7">
                <p><a href="{% url 'goods:eleproduct_list' %}"><strong>更多电子产品</strong></a></p>
            </div>
        </div>
        <div class="col-lg-10 col-lg-offset-1 BodyHeight">
            <div class="Info">
                {% for eleproduct in goods_eleproducts %}
                    <div class="goods {% if forloop.counter == 1 or forloop.counter == 6 %} six {% endif %}">
                        <a href="{% url 'goods:eleproduct_detail' eleproduct.id %}"><img src="{{ MEDIA_URL }}{{ eleproduct.goodsimage_set.all.first.image }}"/></a><p>{{ eleproduct.goods_title }}</p>
                        <span class="price">{{ eleproduct.price }}</span><span>{{ eleproduct.add_time|date:"Y-m-d" }}</span>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<!--其他-->
<section class="other">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 HeaderHeight">
            <div class="col-lg-2">
                <p><strong>其他二手</strong></p>
            </div>
            <div class="col-lg-2 col-lg-offset-7">
                <p><a href="{% url 'goods:other_list' %}"><strong>更多其他二手</strong></a></p>
            </div>
        </div>
        <div class="col-lg-10 col-lg-offset-1 BodyHeight">
            <div class="Info">
                {% for other in goods_others %}
                    <div class="goods {% if forloop.counter == 1 or forloop.counter == 6 %} six {% endif %}">
                        <a href="{% url 'goods:other_detail' other.id %}"><img src="{{ MEDIA_URL }}{{ other.goodsimage_set.all.first.image }}"/></a><p>{{ other.goods_title }}</p>
                        <span class="price">{{ other.price }}</span><span>{{ other.add_time|date:"Y-m-d" }}</span>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<section>
<div class="totop">

</div>
</section>
{% endblock %}

templates/pubsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    .content{
        margin-left: 300px;
        margin-top: 100px;
    }
    .content span a{
        font-size: 16px;
        text-decoration: none;
        cursor: pointer;
    }
</style>
<body>
{% if status == 1 %}
    <div class="content">
    <h2>{{ msg }}</h2>
        <span><a href="{% url 'index' %}">返回首页</a></span>
        <span><a href="{% url 'operation:pubinfo' %}">继续发布</a></span>
        <span><a href="#"></a>进入个人中心</span>
    </div>
{% else %}
    <div class="content">
    <h2>{{ msg }}</h2>
    <span><a href="{% url 'index' %}">返回首页</a></span>
    <span><a href="{% url 'operation:pubinfo' %}">重新发布</a></span>
    </div>
{% endif %}
</body>
</html>

templates/search_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    搜索列表页
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block bread %}
<section class="bread">
    <div class="row">
        <div class="col-lg-offset-1 col-lg-10">
            <div class="breadDiv">
                <span><a href="{% url 'index' %}">首页</a></span><span>&nbsp;>&nbsp;</span><span>搜索信息如下：</span>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="content">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <ul class="contentul">
            {% for search in search_list %}
            <li class="contentli">
                <div class="col-lg-12 {% if forloop.first %} contentDiv1 {% else %} contentDiv2 {% endif %}">
                    <div>
                        <div class="contentleft">
                            {% if search.category == 1 %}
                                <a href="{% url 'goods:book_detail' search.id %}" target="_blank"><img src="{{ MEDIA_URL }}{{ search.goodsimage_set.all.first.image }}"/></a>
                            {% elif search.category == 2 %}
                                <a href="{% url 'goods:tool_detail' search.id %}" target="_blank"><img src="{{ MEDIA_URL }}{{ search.goodsimage_set.all.first.image }}"/></a>
                            {% elif search.category == 3 %}
                                <a href="{% url 'goods:eleproduct_detail' search.id %}" target="_blank"><img src="{{ MEDIA_URL }}{{ search.goodsimage_set.all.first.image }}"/></a>
                            {% elif search.category == 4 %}
                                <a href="{% url 'goods:other_detail' search.id %}" target="_blank"><img src="{{ MEDIA_URL }}{{ search.goodsimage_set.all.first.image }}"/></a>
                            {% endif %}
                        </div>
                        <div class="contentright">
                            <p>
                            {% if search.category == 1 %}
                                <a href="{% url 'goods:book_detail' search.id %}" target="_blank">{{ search.goods_title }}</a>
                            {% elif search.category == 2 %}
                                <a href="{% url 'goods:tool_detail' search.id %}" target="_blank">{{ search.goods_title }}</a>
                            {% elif search.category == 3 %}
                                <a href="{% url 'goods:eleproduct_detail' search.id %}" target="_blank">{{ search.goods_title }}</a>
                            {% elif search.category == 4 %}
                                <a href="{% url 'goods:other_detail' search.id %}" target="_blank">{{ search.goods_title }}</a>
                            {% endif %}
                                <span>{{ tool.price }}</span></p>
                            <p>{{ tool.description | slice:":30" }}.......</p>
                            <br>
                            <p>发布时间：{{ tool.add_time|date:"Y-m-d" }}</p>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}

        </ul>
    </div>
</div>
</section>
{% endblock %}

templates/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>email密码修改</title>
</head>
<body>
<form method="post" action="{% url 'users:sendemail' %}">
    <label>邮箱号码：</label><input type="text" name="email">
    <input type="submit" value="发送修改连接">
    {% csrf_token %}
</form>
</body>
</html>

templates/tool_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    机动类列表
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block bread %}
<section class="bread">
    <div class="row">
        <div class="col-lg-offset-1 col-lg-10">
            <div class="breadDiv">
                <span><a href="{% url 'index' %}">首页</a></span><span>&nbsp;>&nbsp;</span><span>二手机动</span>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="content">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <ul class="contentul">
            {% for tool in goods_tools %}
            <li class="contentli">
                <div class="col-lg-12 {% if forloop.first %} contentDiv1 {% else %} contentDiv2 {% endif %}">
                    <div>
                        <div class="contentleft">
                            <a href="{% url 'goods:tool_detail' tool.id %}"><img src="{{ MEDIA_URL }}{{ tool.goodsimage_set.all.first.image }}"/></a>
                        </div>
                        <div class="contentright">
                            <p><a href="{% url 'goods:tool_detail' tool.id %}">{{ tool.goods_title }}</a><span>{{ tool.price }}</span></p>
                            <p>{{ tool.description | slice:":30" }}.......</p>
                            <br>
                            <p>发布时间：{{ tool.add_time|date:"Y-m-d" }}</p>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}

        </ul>
    </div>
</div>
</section>
{% endblock %}